name: crms
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  bloc: ^8.1.0
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.1
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_verification_code: ^1.1.6
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  lottie: ^2.0.0
  textfield_datepicker: ^0.1.0
  shared_preferences: ^2.0.15
  curved_navigation_bar: ^1.0.3
  image_picker: ^0.8.6
  firebase_storage: ^11.0.10
  dropdown_textfield: ^1.0.7
  dropdown_button2: ^1.9.2
  url_launcher: ^6.1.7
  flutter_pdfview: ^1.2.5

  flutter_document_picker: ^5.1.0
  file_picker: ^5.2.5
  path: ^1.8.2
  rxdart: ^0.27.7
  fluttertoast: ^8.1.2
  firebase_database: ^10.0.9
dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
      - assets/images/

